server {

    listen 80;
    server_name j14a406.p.ssafy.io;

    # HTTP 요청을 HTTPS로 자동 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}



server {

    listen 443 ssl;
    server_name j14a406.p.ssafy.io;

    # 발급받은 인증서 경로 설정
    ssl_certificate /etc/letsencrypt/live/j14a406.p.ssafy.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/j14a406.p.ssafy.io/privkey.pem;

    # TLS 세션 재사용(세션 캐시) 유효기간 -> 1일
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    # 허용 TLS 버전
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        # 나중에 백엔드나 프론트엔드로 프록시 설정할 곳
        root /usr/share/nginx/html;
        index index.html;
    }
}

